### ISSUE TITLE
MSSQL support

### ISSUE THREAD

**Issue by everplays** [yandex-money-tech/db-queue#3]
Even though I wanted to work on introducing priorities within one worker thread as we discussed in #1, the support for MSSQL got higher priority for us. So I focused on implementing mssql driver for db-queue.

So far, I have managed to implement the main classes: `MssqlQueueDao`, `MssqlQueuePickTaskDao`, and accompanying test classes. However, I want to clear out a couple of things before I make the PR:

- are you willing to accept a PR to support MSSQL directly in `db-queue`?
- **a: if yes**, how should we manage the databases in tests? right now, embedded postgres is used. However, that can't be the case for mssql. Should we assume that both of them will be executed externally? (via docker in case of travis-ci).
- **b: if no**, because of the way that `DatabaseDialect` is implemented and used, users of library can not add support for other databases. I think we need to have an implementation registry of sort so dialects can be added dynamically.

**Comment by f0y** [comment]
Yes,  I will accept support for MSSQL.
You can use https://www.testcontainers.org/modules/databases/mssqlserver/ for mssql.

**Comment by everplays** [comment]
Closing this as the PR was merged by f0y.

**Comment by f0y** [comment]
Fixed in https://bintray.com/yandex-money-tech/maven/db-queue/8.3.0
